In [1]:
import numpy as np

# Check version
print("NumPy version:", np.__version__)

NumPy version: 2.4.3


In [2]:
# Creating arrays
list1 = [1, 2, 3, 4, 5]          # regular Python list
arr1 = np.array([1, 2, 3, 4, 5]) # NumPy array

print("Python list:", list1)
print("NumPy array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)
print("Data type:", arr1.dtype)

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data type: int64


In [9]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("2D Arrary: \n", arr2d)
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Total Elements:", arr2d.size)


2D Arrary: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Total Elements: 9


In [12]:
print("Element at 0 row and 1st column", arr2d[0, 1])
print("Element at 2 row and 2nd column", arr2d[2, 2])

Element at 0 row and 1st column 2
Element at 2 row and 2nd column 9


In [13]:
print("first row:", arr2d[0])
print("last row:", arr2d[-1])

first row: [1 2 3]
last row: [7 8 9]


In [18]:
print("first column:", arr2d[:,0])
print("second column:", arr2d[:,1])

first column: [1 4 7]
second column: [2 5 8]


In [19]:
print("Top right 2x2 block:\n", arr2d[0:2, 1:3])

Top right 2x2 block:
 [[2 3]
 [5 6]]


In [20]:
# Array Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Math operations apply to every element automatically
print("Addition:", arr1 + arr2)
print("Subtraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Scalar operations (single number applied to every element)
print("\nMultiply every element by 2:", arr1 * 2)
print("Add 10 to every element:", arr1 + 10)
print("Square every element:", arr1 ** 2)

# Useful math functions
print("\nSum of all elements:", arr1.sum())
print("Mean (average):", arr1.mean())
print("Max value:", arr1.max())
print("Min value:", arr1.min())

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]

Multiply every element by 2: [ 2  4  6  8 10]
Add 10 to every element: [11 12 13 14 15]
Square every element: [ 1  4  9 16 25]

Sum of all elements: 15
Mean (average): 3.0
Max value: 5
Min value: 1


In [25]:
arr2d = np.array([[1, 2, 3], [5,6,7], [9,10,11], [7,9,2]])
print("Shape :", arr2d.shape)
print("Dimensions :", arr2d.ndim)
print("Total Elements :", arr2d.size)

Shape : (4, 3)
Dimensions : 2
Total Elements : 12


In [26]:
print("Second row column one :", arr2d[1,0])

Second row column one : 5


In [27]:
print("Second row :", arr2d[1]);

Second row : [5 6 7]


In [30]:
print("bottom 2*2 block :", arr2d[1:4, 1:3])

bottom 2*2 block : [[ 6  7]
 [10 11]
 [ 9  2]]


In [43]:
arr1d1 = np.array([1, 2, 3, 4, 5])
arr1d2 = np.array([10, 11, 12, 13, 14])
arr1d3= np.array(arr1d1 * arr1d2)
print("The multiplied arrays :", arr1d3)
print("The sum values of the array : ", arr1d3.sum)
print("The mean values of the array: ", arr1d3.mean)
print("The max values of the array: ", arr1d3.max)




The multiplied arrays : [10 22 36 52 70]
The sum values of the array :  <built-in method sum of numpy.ndarray object at 0x11281bf90>
The mean values of the array:  <built-in method mean of numpy.ndarray object at 0x11281bf90>
The max values of the array:  <built-in method max of numpy.ndarray object at 0x11281bf90>


In [45]:
arr1d = np.array([11, 21, 31, 41, 51, 61])
arr1d2 = arr1d - 5
arr1d3 = arr1d2 ** 2
print("the new arrays after subtracting 5 and then performing square is: ", arr1d3)

the new arrays after subtracting 5 and then performing square is:  [  36  256  676 1296 2116 3136]


In [47]:
arr2d = np.array([[1, 2, 3], [5,6,7], [9,10,11], [7,9,2]])
print("Shape :", arr2d.shape)
print("Dimensions :", arr2d.ndim)
print("Total Elements :", arr2d.size)
print("Second row column one :", arr2d[1,0])
print("Second row :", arr2d[1]);
print("bottom 2*2 block :", arr2d[1:4, 1:3])
arr1d1 = np.array([1, 2, 3, 4, 5])
arr1d2 = np.array([10, 11, 12, 13, 14])
arr1d3= np.array(arr1d1 * arr1d2)
print("The multiplied arrays :", arr1d3)
print("The sum values of the array : ", arr1d3.sum())
print("The mean values of the array: ", arr1d3.mean())
print("The max values of the array: ", arr1d3.max())
arr1d = np.array([11, 21, 31, 41, 51, 61])
arr1d2 = arr1d - 5
arr1d3 = arr1d2 ** 2
print("the new arrays after subtracting 5 and then performing square is: ", arr1d3)



Shape : (4, 3)
Dimensions : 2
Total Elements : 12
Second row column one : 5
Second row : [5 6 7]
bottom 2*2 block : [[ 6  7]
 [10 11]
 [ 9  2]]
The multiplied arrays : [10 22 36 52 70]
The sum values of the array :  190
The mean values of the array:  38.0
The max values of the array:  70
the new arrays after subtracting 5 and then performing square is:  [  36  256  676 1296 2116 3136]
